version: '3'

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    env_file:
      - .env

  backend:
    build: ./backend
    depends_on:
      - database

  telegram_bot:
    build: ./telegram_bot
    depends_on:
      - database
      - backend